import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import * as Material from '@angular/material';

@NgModule({
  declarations: [],
  imports: [
    CommonModule,
    Material.MatToolbarModule,
    Material.MatCardModule,
    Material.MatTabsModule,
    Material.MatDividerModule,
    Material.MatSliderModule,
    Material.MatSelectModule,
    Material.MatRadioModule,
    Material.MatNativeDateModule,
    Material.MatDatepickerModule,
    Material.MatSnackBarModule,
    Material.MatIconModule,
    Material.MatDialogModule,
    Material.MatProgressSpinnerModule,
    Material.MatButtonModule,
    Material.MatSortModule,
    Material.MatTableModule,
    Material.MatTabsModule, 
    Material.MatCheckboxModule, 
    Material.MatCardModule,
    Material.MatFormFieldModule, 
    Material.MatProgressSpinnerModule, 
    Material.MatInputModule, 
    Material.MatPaginatorModule,
    Material.MatListModule,
    Material.MatTooltipModule,
    Material.MatMenuModule,
    Material.MatSidenavModule,
    Material.MatAutocompleteModule,
    Material.MatGridListModule
  ],
  exports: [
    Material.MatToolbarModule,
    Material.MatCardModule,
    Material.MatTabsModule,
    Material.MatDividerModule,
    Material.MatSliderModule,
    Material.MatSelectModule,
    Material.MatRadioModule,
    Material.MatNativeDateModule,
    Material.MatDatepickerModule,
    Material.MatSnackBarModule,
    Material.MatIconModule,
    Material.MatDialogModule,
    Material.MatProgressSpinnerModule,
    Material.MatButtonModule,
    Material.MatSortModule,
    Material.MatTableModule,
    Material.MatTabsModule, 
    Material.MatCheckboxModule, 
    Material.MatCardModule,
    Material.MatFormFieldModule, 
    Material.MatProgressSpinnerModule, 
    Material.MatInputModule, 
    Material.MatPaginatorModule,
    Material.MatListModule,
    Material.MatTooltipModule,
    Material.MatMenuModule,
    Material.MatSidenavModule,
    Material.MatAutocompleteModule,
    Material.MatGridListModule

  ]
})
export class MaterialModule { }
